# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0002_auto_20171104_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=255, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=255, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Segundo apellido')),
                ('correo', models.EmailField(max_length=50, unique=True, verbose_name='Correo electrónico')),
                ('tipo_identificacion', models.SmallIntegerField(choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Pasaporte')], verbose_name='Tipo de identificación')),
                ('numero_identificacion', models.CharField(max_length=50, unique=True, verbose_name='Número de Identificación')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('rh', models.SmallIntegerField(blank=True, choices=[(0, 'A+'), (1, 'A-'), (2, 'B+'), (3, 'B-'), (4, 'AB+'), (5, 'AB-'), (6, 'O+'), (7, 'O-')], null=True, verbose_name='RH')),
                ('eps', models.CharField(blank=True, max_length=50, null=True, verbose_name='EPS')),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles')),
                ('telefono', models.CharField(max_length=50, verbose_name='Número')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('acudiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
                ('grupos_dirige', models.ManyToManyField(blank=True, null=True, to='grupos.Grupo')),
            ],
            options={
                'permissions': (('view_persona', 'Puede ver personas'),),
            },
        ),
    ]
