# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'permissions': (('view_rol', 'Puede ver roles'),),
            },
        ),
        migrations.RemoveField(
            model_name='persona',
            name='acudiente',
        ),
        migrations.AddField(
            model_name='persona',
            name='acudiente',
            field=models.ManyToManyField(blank=True, null=True, to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='personas.Rol'),
        ),
    ]
