# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20171105_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Identificación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Pasaporte')], null=True, verbose_name='Tipo de identificación'),
        ),
    ]
