# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-05 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20171105_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='grupos_dirige',
            field=models.ManyToManyField(blank=True, null=True, to='grupos.Grupo', verbose_name='Grupos que dirige'),
        ),
    ]
