# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20171105_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
