# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_remove_persona_grupos_dirige'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Número Telefónico'),
        ),
    ]
