# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_auto_20171113_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.SmallIntegerField(choices=[(0, 'Aprendiz'), (1, 'Aspirante'), (2, 'Director')], default=2),
        ),
    ]
