# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0011_auto_20171119_1559'),
        ('personas', '0012_auto_20171120_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(verbose_name='Fecha limite')),
                ('estado', models.SmallIntegerField(choices=[(0, 'Sin empezar'), (1, 'En proceso'), (2, 'Finalizada')], default=0)),
                ('grupos_responsable', models.ManyToManyField(blank=True, null=True, to='grupos.Grupo', verbose_name='Grupo responsable')),
                ('persona_responsable', models.ManyToManyField(blank=True, null=True, to='personas.Persona', verbose_name='Persona responsable')),
            ],
        ),
    ]
