# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_tarea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'permissions': (('view_tarea', 'Puede ver tareas'),)},
        ),
    ]
