# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0013_auto_20171120_2339'),
        ('personas', '0014_auto_20171122_0144'),
    ]

    operations = [
    ]
