# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0015_merge_20171121_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(verbose_name=b'Descripci\xc3\xb3n'),
        ),
    ]
