# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0017_auto_20171205_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_parentezco',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Madre'), (1, 'Padre'), (2, 'Hermano(a)'), (3, 'Abuelo(a)'), (4, 'Tio(a)')], null=True, verbose_name='Parentezco*'),
        ),
    ]
