# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0018_auto_20171210_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'permissions': (('view_persona', 'Puede ver personas'), ('view_acudiente', 'Puede ver acudiente'), ('add_acudiente', 'Puede agregar acudiente'), ('change_acudiente', 'Puede modificar acudiente'), ('delete_acudiente', 'Puede eliminar acudiente'))},
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='Correo electrónico*'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Identificación*'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_identificacion',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Cédula de Ciudadanía'), (1, 'Tarjeta de Identidad'), (2, 'Pasaporte')], null=True, verbose_name='Tipo de Identificación*'),
        ),
    ]
