# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '0009_auto_20171113_1525'),
        ('personas', '0008_auto_20171113_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'permissions': (('view_personaje', 'Puede ver personajes'),),
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_interpretacion', models.DateField(verbose_name='Fecha de interpretación')),
                ('valor_boleta', models.FloatField(verbose_name='Valor de la boleta')),
                ('lugar', models.CharField(max_length=512, verbose_name='Lugar')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos', verbose_name='Imagen')),
                ('estado', models.BooleanField(default=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona', verbose_name='Director')),
                ('grupos', models.ManyToManyField(to='grupos.Grupo', verbose_name='Grupos')),
            ],
            options={
                'permissions': (('view_proyecto', 'Puede ver proyectos'),),
            },
        ),
        migrations.AddField(
            model_name='personaje',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proyecto', to='proyectos.Proyecto'),
        ),
    ]
