# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20171113_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
