# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_auto_20171114_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_interpretacion',
            field=models.DateField(verbose_name='Fecha de interpretación'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='valor_boleta',
            field=models.FloatField(verbose_name='Valor Boleta'),
        ),
    ]
