# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_auto_20171119_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_interpretacion',
            field=models.DateField(verbose_name=b'Fecha de interpretaci\xc3\xb3n'),
        ),
    ]
