# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_auto_20171120_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='autor',
            field=models.CharField(default='Creaci\xf3n colectiva', max_length=255, verbose_name=b'Autor*'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='video',
            field=models.CharField(default='No hay', max_length=500, verbose_name=b'Video'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name=b'Nombre*'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona', verbose_name=b'Interprete*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_interpretacion',
            field=models.DateField(verbose_name=b'Fecha de Interpretaci\xc3\xb3n*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(default='no hay', upload_to=b'proyectos', verbose_name=b'Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name=b'Nombre*'),
        ),
    ]
