# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20171126_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción*'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona', verbose_name='Aprendiz*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='autor',
            field=models.CharField(max_length=255, verbose_name='Autor*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona', verbose_name='Director*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_interpretacion',
            field=models.DateField(verbose_name='Fecha de Interpretación*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='grupos',
            field=models.ManyToManyField(to='grupos.Grupo', verbose_name='Grupos*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(upload_to='proyectos', verbose_name='Imagen*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='lugar',
            field=models.CharField(max_length=512, verbose_name='Lugar*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='video',
            field=models.CharField(max_length=500, verbose_name='Video'),
        ),
    ]
