# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name=b'Nombre*')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name=b'Descripci\xc3\xb3n')),
                ('valor_cuota', models.FloatField(verbose_name=b'Valor Cuota*')),
                ('estado', models.BooleanField(default=True, verbose_name=b'Estado')),
            ],
            options={
                'permissions': (('view_categoria', 'Puede ver categorias'),),
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name=b'Nombre*')),
                ('descripcion', models.TextField(max_length=57, verbose_name=b'Descripci\xc3\xb3n*')),
                ('estado', models.BooleanField(default=True, verbose_name=b'Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n')),
                ('fecha_inactivacion', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha de inactivaci\xc3\xb3n')),
            ],
            options={
                'permissions': (('view_grupo', 'Puede ver grupos'),),
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.FloatField(verbose_name=b'Valor pagado*')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de pago')),
                ('alerta_pago', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Grupo', verbose_name=b'Grupo*')),
            ],
            options={
                'permissions': (('view_pago', 'Puede ver pagos'),),
            },
        ),
    ]
