# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'permissions': (('view_categoria', 'Puede ver categorias'),)},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'permissions': (('view_grupo', 'Puede ver grupos'),)},
        ),
    ]
