# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona', verbose_name=b'Aprendiz*'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.Categoria', verbose_name=b'Categoria*'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Director', to='personas.Persona', verbose_name=b'Director*'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='Estudiantes', to='personas.Persona', verbose_name=b'Aprendices'),
        ),
    ]
