# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
