# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_pago_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grupo', to='grupos.Grupo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Estudiante', to='personas.Persona'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor_pago',
            field=models.FloatField(verbose_name='Valor pagado'),
        ),
    ]
