# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_rol_estado'),
        ('grupos', '0006_auto_20171108_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='estudiantes',
            field=models.ManyToManyField(to='personas.Persona', verbose_name='Estudiantes'),
        ),
    ]
