# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_remove_persona_grupos_dirige'),
        ('grupos', '0007_grupo_estudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Director', to='personas.Persona', verbose_name='Director'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='estudiantes',
            field=models.ManyToManyField(related_name='Estudiantes', to='personas.Persona', verbose_name='Estudiantes'),
        ),
    ]
