# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0008_auto_20171108_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='valor_cuota',
            field=models.FloatField(verbose_name='Valor Cuota'),
        ),
    ]
