# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0009_auto_20171113_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name=b'Descripci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de creaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='fecha_inactivacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha de inactivaci\xc3\xb3n'),
        ),
    ]
