# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0013_auto_20171205_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 12, 11, 0, 24, 6, 28138, tzinfo=utc), verbose_name='Fecha de pago'),
            preserve_default=False,
        ),
    ]
